#!/usr/bin/python

import yaml
import os
import subprocess
import sys
import random
import socket
import threading
import functools

# Handle the SSH tunnel process

class SSHUProcess:
    def __init__(self, info):
#        print "Info is {}".format(info)
        self.host = info['ssh+nc']
        self.sport = random.randrange(10000, 20000)
        self.dport = random.randrange(10000, 20000)

    def __enter__(self):
#        nccmd='while nc -U /var/run/docker.sock; do echo > /dev/null; done'
        nccmd='coproc nc -U /var/run/docker.sock; nc -l {dport} <&${{COPROC[0]}} >&${{COPROC[1]}}'.format(dport=self.dport)
        cmd = "ssh -L {sport}:localhost:{dport} {host} '{nccmd}' ".format(host=self.host, sport=self.sport, nccmd = nccmd, dport = self.dport)

        def launch():
            while True:
                self.process = subprocess.Popen(cmd, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
                self.process.wait()

        self.start(launch)

        return "localhost:{}".format(self.sport)

    def start(self, proc):
        t = threading.Thread(target=proc)
        t.daemon = True
        t.start()

    def __exit__(self, type, value, traceback):
#        print "Terminating {}".format(self.process)
        self.process.terminate()
        self.process.wait()

class SSHProcess:
    def __init__(self, info):
#        print "Info is {}".format(info)
        self.host = info['ssh']
        if 'port' in info:
            self.dport = info['port']
        else:
            self.dport = 2375
        self.sport = random.randrange(10000, 20000)

    def __enter__(self):
#        print "Launching SSH to {host}:{port} from {sport}".format(host=self.host, sport=self.sport, port=self.dport)
        cmd = "ssh {host} -L {sport}:localhost:{dport} -N".format(host=self.host, sport=self.sport, dport=self.dport)
        self.process = subprocess.Popen(cmd, shell=True)
        return "localhost:{}".format(self.sport)

    def __exit__(self, type, value, traceback):
#        print "Terminating {}".format(self.process)
        self.process.terminate()
        self.process.wait()

# Handle direct connections
class Direct:
    def __init__(self, info):
        self.address = info['address']
        if 'port' in info:
            self.dport = info['port']
        else:
            self.dport = 2375

    def __enter__(self):
        return "{}:{}".format(self.address, self.dport)

    def __exit__(self, type, value, traceback):
        pass
    
# Decide what connection type is appropriate and return it
def connect(info):
    if 'ssh' in info:
        return SSHProcess(info)
    elif 'ssh+nc' in info:
        return SSHUProcess(info)
    elif 'address' in info:
        return Direct(info)
    else:
        raise Exception("Can't determine connection method for {}".format(info))

FILE="~/.dockerenv"

def main():
    if not os.path.isfile(os.path.expanduser(FILE)):
        print "Cannot find index file {}".format(FILE)
        sys.exit(1)

    with open(os.path.expanduser(FILE), "r") as input:
        data = yaml.load(input)

    if data is None: raise Exception("Must have data")
    if len(sys.argv) < 2: 
        for name in data:
            print name
        sys.exit(0)

    name = sys.argv[1]

    shell = "bash"
    if "SHELL" in os.environ:
        shell = os.environ["SHELL"]

    if not name in data:
        print "Unknown docker environment '{}'".format(name)
        print "Available options:"
        for name in data:
            print "  " + name
        sys.exit(1)

    try:
        with connect(data[name]) as var:
            newenv = os.environ.copy()
            newenv["DOCKER_HOST"] = var
            newenv["PS1"] = "\\n({name}){ps1}".format(name=name, var=var, ps1=os.environ["PS1"])

            cmd = "{shell} --norc".format(shell=shell)
            try:
#                print "Launching shell in {}".format(cmd)
                subprocess.call([shell, "--norc"] , env=newenv)
                print "Shell complete"
            except OSError as e:
                print "Error launching SSH process '{}': {}".format(cmd, e)
                sys.exit(1)

    except OSError as e:
        print "Error launching SSH process '{}':{}".format(cmd, e)
        sys.exit(1)


if __name__ == "__main__":
    main()
